config/routes.rb
Rails.application.routes.draw do
  resources :accounts do
    member do
      post 'transfer', to: "accounts#transfer", as: "amount"
      get 'transfer'
    end
  end
  root 'accounts#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :find_account, only: [:show, :edit, :update, :destroy]

	def index
        @accounts= Account.all
	end

	def new
		@account = Account.new
	end

	def show
	end

	def transfer
		puts "******************"
		if params[:account]
			@sender = Account.find params[:id]
			@reciever = Account.find params[:account]
			@ramount = @reciever.account_balance + params[:amount].to_f
			@reciever.update(:account_balance => @ramount)
			@samount = @sender.account_balance - params[:amount].to_f
			
			@sender.update(:account_balance => @samount)
		end
			
	end

	def create
		@account = Account.new(account_params)
		if @account.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def update
		if @account.update_attributes(account_params)
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def edit
	end

	def destroy
		@account.destroy
		redirect_to root_path
	end

	private

	def account_params
			params.require(:account).permit(:firstname, :lastname, :dob, :account_balance, :address)
	end

	def find_account
		@account = Account.find(params[:id])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for @account do |f| %>
    <p> Firstname:</br> <%= f.text_field :firstname%> </p>
    <p> Lastname:</br> <%= f.text_field :lastname%> </p>
    <p> balance:</br> <%= f.text_field :account_balance%> </p>
    <p> adress:</br> <%= f.text_field :address%> </p>
    <p> DOB:</br> <%= f.text_field :dob%> </p>
    <%= f.submit :create %>
  <% end %>
</div>

app/views/accounts/edit.html.erb
  <h1>Edit</h1>
  <%= form_for @account do |f| %>
    <p> Firstname:</br> <%= f.text_field :firstname%> </p>
    <p> Lastname:</br> <%= f.text_field :lastname%> </p>
    <p> balance:</br> <%= f.text_field :account_balance%> </p>
    <p> adress:</br> <%= f.text_field :address%> </p>
    <p> DOB:</br> <%= f.text_field :dob%> </p>
    <%= f.submit :update %>
  <% end %>

app/views/accounts/index.html.erb
<h1>Welcome to Bank</h1>
<h1>Following are the available bank accounts</h1>
<% @accounts.each do |f| %>
<h2><%= link_to f.firstname, account_path(f) %></h2>
<% end %>

<%= link_to "new account", new_account_path %>

app/views/accounts/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

app/views/accounts/show.html.erb
<h2>Firstname: <%= @account.firstname %></h2>
<h2>Lastname: <%= @account.lastname %></h2>
<h2>DOB: <%= @account.dob %></h2>
<h2>address: <%= @account.address %></h2>
<h2>balance: <%= number_to_currency(@account.account_balance) %></h2>
<%= link_to "Transfer", amount_account_path(@account) %>
<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_account_path %>
<%= link_to "Delete", account_path(@account), method: :delete, data: { confirm: "Are you sure?"}%>

app/views/accounts/transfer.html.erb
<%= form_tag "transfer" do %>
	
	To Account:<%= select_tag "account", options_from_collection_for_select(Account.all, "id", "firstname") %> <br />
	<%= text_field_tag :amount %><br />
	<%= submit_tag %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BankApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>